# Configuración para Nginx del Host (VPS)
# Ubicación típica: /etc/nginx/sites-available/craneflow.juliobendezu.com

server {
    listen 80;
    server_name craneflow.juliobendezu.com;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl; # managed by Certbot
    server_name craneflow.juliobendezu.com;

    # SSL managed by Certbot (estos lines los añade certbot --nginx)
    # ssl_certificate /etc/letsencrypt/live/craneflow.juliobendezu.com/fullchain.pem;
    # ssl_certificate_key /etc/letsencrypt/live/craneflow.juliobendezu.com/privkey.pem;

    location / {
        proxy_pass http://127.0.0.1:5080; # Puerto que mapeamos en docker-compose para el frontend
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Configuración CRÍTICA para SignalR (WebSockets)
    location /cranehub {
        proxy_pass http://127.0.0.1:5001/cranehub; # Puerto que mapeamos en docker-compose para el backend
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        
        # Opcional: Aumentar timeouts para evitar desconexiones
        proxy_read_timeout 3600;
        proxy_send_timeout 3600;
    }

    location /api {
        proxy_pass http://127.0.0.1:5001/api; # Puerto que mapeamos en docker-compose para el backend
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection keep-alive;
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
